# Generated by Django 5.1.1 on 2024-12-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="description",
            field=models.TextField(default="dsadsasdsadasd"),
            preserve_default=False,
        ),
    ]
