# Generated by Django 5.1.1 on 2024-12-09 17:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, default="", upload_to="profile_images/"
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("surname", models.CharField(default="", max_length=100)),
                (
                    "profession",
                    models.CharField(
                        default="",
                        help_text="Profession. eg. Software Developer",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Organization/Institution",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Your website/blog URL.",
                        null=True,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
